var tip1 = {
	id : 1,
	title : "Data Storage",
	urlIds : [ 10, 11, 12, 13, 14, 15, 53 ],
	content : [
			"<h4>Introduction:</h4>",
			"As we know, we can store data with specific DOM elements by using JQuery.",
			"Data can store in DOM elements as static and dynamic.",
			"<h4>Purpose:</h4>",
			"To store Data in specific DOM elements for both static and dynamic",
			"<h4>Step to do:</h4>",
			"<strong>1. Import JQuery Library bellow:</strong>",
			"<div class='code_container'><pre class='code_block'><code><</code>script type=\"text/javascript\" src=\"https://ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js\"<code>></code><code><</code>/script<code>></code></pre></div>",
			"<strong>2. Store Data in inline elements as Static</strong>",
			"2.1 To store Data in specific DOM elements",
			"a. Syntax:",
			"<div class='code_container'><pre class='code_block'>data-variable_name=\"value\"</pre></div>",
			"b. Example:",
			"<div class='code_container'><pre class='code_block'><code><</code>li data-action=\"checkproduct/v10\"Download Product Checklists<code>></code><code><</code>/li<code>></code></pre></div>",
			"2.2. Get Data from specific DOM elements",
			"a. Syntax:",
			"<div class='code_container'><pre class='code_block'>DOM_elements.data(variable_name)</pre></div>",
			"b. Example:",
			"<div class='code_container'><pre class='code_block'>$('li').data('action')</pre></div>",
			"<strong>3. Store Data in inline elements as Dynamic</strong>",
			"3.1 To store Data in specific DOM elements",
			"<div class='code_container'><pre class='code_block'>We must convert JSon Object into String because Data store in specific DOM elements as String.",
			"To convert from JSon Object to String by:",
			"JSON.stringify(opt)",
			"where opt is JSON Object.</pre></div>",
			"a. Syntax:",
			"<div class='code_container'><pre class='code_block'>data-variable_name=\"value\"</pre></div>",
			"b. Example:",
			"<div class='code_container'><pre class='code_block'><code><</code>input type='text' data-option='\"+JSON.stringify(opt)+\"' value='\" + opt.label + \"' required='required'/<code>></code></pre></div>",
			"3.2. Get Data from specific DOM elements",
			"a. Syntax:",
			"<div class='code_container'><pre class='code_block'>DOM_elements.data(variable_name)</pre></div>",
			"b. Example:",
			"<div class='code_container'><pre class='code_block'>var option = $(\"#\"+ index + \"_option_\" + questionNumber + \"_question_label\").data('option');",
			"The value of option is JSON Object.",
			"So it does not required us to convert from String to JSON Object.</pre></div>",
			"c. Store Data to overide on inline DOM elements",
			"<div class='code_container'><pre class='code_block'>//Remove data-option attribute from inline DOM elements",
			"button.removeAttr(\"data-option\");",
			"//Remove option from Data Storage",
			"button.removeData('option');", "//Store Option in Dom",
			"button.data('option', option);</pre></div>" ]
};