var tip5 = {
	id : 5,
	title : "HTML & CSS Tips",
	urlIds : [52, 54, 67],
	content : [
				"<h4>Introduction:</h4>",
				"Jquery provides us clearly document about jQuery API. For this study is to note some tips for using Jquery.",
				"<h4>Purpose:</h4>",
				"To know some methods amount hunred of Jquery methods.",
				"<h4>Tips:</h4>",
				"<strong>1. Using selector.css():</strong>",
				"<strong>a. Get single value from CSS:</strong>",
				"<div class='code_container'><pre class='code_block'>var color = $( <strong>seletor</strong> ).css( \"background-color\" );",
				"So we can get color code from <strong>selector</strong>.</pre></div>",
				"<strong>b. Get multiple values from CSS:</strong>",
				"<div class='code_container'><pre class='code_block'>var styleProps = $( <strong>seletor</strong> ).css([\"width\", \"height\", \"color\", \"background-color\"]);",
				"styleProps is the multiple style properties from <strong>selector</strong>.</pre></div>",
				"<strong>c. Set single value to CSS:</strong>",
				"<div class='code_container'><pre class='code_block'>$(\"<strong>ul.ui-autocomplete</strong>\").css(\"width\",\"200\");",
				"Where $(\"<strong>ul.ui-autocomplete</strong>\") is <strong>seletor</strong> object.</pre></div>",
				"<strong>c. Set multiple values to CSS:</strong>",
				"<div class='code_container'><pre class='code_block'>Here is first style:",
				"<strong>$(\"test\").css({</strong>",
				"	\"background-color\": \"yellow\",",
				"	\"font-weight\": \"bolder\"",
				"<strong>})</strong>;",
				"	",
				"Here is second style:",
				"<strong>var styles = {</strong>",
				"	backgroundColor : \"#ddd\",",
				"	fontWeight : \"bold\"",
				"<strong>}</strong>;",
				"	",
				"$(\"#test\").css( <strong>styles</strong> );",
				"</pre></div>",
				"<strong>2. General Attributes such as get, add, remove, and is disabled attributes:</strong>",
				"<strong>a. Get attribute value from selector:</strong>",
				"<div class='code_container'><pre class='code_block'>var key = <strong>$(\"a[id^='up_']:first\")</strong>.attr(\"<strong>id</strong>\").substring(\"down_\".length);",
				"console.log(key);",
				"</pre></div>",
				"<strong>b. Set attribute value to a selector:</strong>",
				"<div class='code_container'><pre class='code_block'>//Add Disabled attribute to first move up and last move down",
				"<strong>$(\"a[id^='up_']:first\")</strong>.attr(\"<strong>disabled</strong>\", \"<strong>disabled</strong>\");",
				"<strong>$(\"a[id^='down_']:last\")</strong>.attr(\"<strong>disabled</strong>\", \"<strong>disabled</strong>\");",
				"</pre></div>",
				"<strong>c. Check selector is disabled status:</strong>",
				"<div class='code_container'><pre class='code_block'>//Check Disabled attribute status",
				"<strong>if($(\"a[id^='up_']:first\")</strong>.<strong>is</strong>(\"<strong>:disabled</strong>\"))<strong>{</strong>",
				"	console.log(\"This is disable status\");",
				"<strong>}</strong></pre></div>",
				"<strong>d. Remove attribute from selector:</strong>",
				"<div class='code_container'><pre class='code_block'>//Remove all Disabled attribute from a selector",
				"<strong>$(\"a[id^='up_']\")</strong>.removeAttr(\"<strong>disabled</strong>\");",
				"<strong>$(\"a[id^='down_']\")</strong>.removeAttr(\"<strong>disabled</strong>\");",
				"</pre></div>",
				"<strong>3. Add, Remove, has, visible, and hidden Class CSS:</strong>",
				"<div class='code_container'><pre class='code_block'>//Remove class \"<strong>ui-corner-all</strong>\" from <strong>$(\"#Test\")</strong> Selector",
				"<strong>$(\"#Test\")</strong>.removeClass( \"<strong>ui-corner-all</strong>\" );",
				"//Add class \"<strong>ui-corner-top</strong>\" to <strong>$(\"#Test\")</strong> selector",
				"<strong>$(\"#Test\")</strong>.addClass( \"<strong>ui-corner-top</strong>\" );",
				"//Has class \"<strong>show-mode</strong>\" to <strong>$(\"#cocktailSources\")</strong> selector",
				"<strong>$(\"#cocktailSources\")</strong>.hasClass( \"<strong>show-mode</strong>\" );",
				"//Visible Class",
				"var isVisible = <strong>$(\"#cocktailSources\")</strong>.is( \"<strong>:visible</strong>\" );",
				"//Hidden Class",
				"var isHidden = <strong>$(\"#cocktailSources\")</strong>.is( \"<strong>:hidden</strong>\" );",
				"</pre></div>",
				"<strong>4. CSS Tips:</strong>",
				"<div class='code_container'><pre class='code_block'><strong>//Display all button lines except last element</strong>",
				"<strong>.reward-white</strong>:not(:<strong>last-child</strong>){",
				"	background-color: #ffffff;",
				"	border-bottom: 1px solid #ddd;",
				"}",
				"",
				"<strong>//Disable all link with attribute \"disabled\"</strong>",
				"<strong>a</strong>[<strong>disabled</strong>]{",
				"	color: grey;",
				"	cursor: default;/*not-allowed*/",
				"}",
				"<strong>a</strong>[<strong>disabled</strong>]:hover {",
				"	text-decoration: none;",
				"}",
				"",
				"<strong>//Find div which has ID starts with \"imagePreview\" to put padding = 10px</strong>",
				"<strong>div</strong>[<strong>id</strong>^='<strong>imagePreview</strong>']{",
				"	padding: 10px;",
				"}",
				"Where \"<strong>imagePreview</strong>\" is the ID of selector",
				"",
				"<strong>//Find div which has ID starts with \"event_\"</strong>",
				"<strong>div</strong>[<strong>id</strong>^='<strong>event_</strong>'] {",
				"	outline: none;",
				"	color: #e78f08;",
				"	font-weight: bold;",
				"}",
				"Where \"<strong>event_</strong>\" is the ID of selector",
				"",
				"<strong>//Find all span under div starts with ID begin by \"tip_\" to format text as ...</strong>",
				"<strong>div</strong>[<strong>id</strong>^='<strong>tip_</strong>'] <strong>span</strong>{",
				"	width: 99%;",
				"	overflow: hidden;",
				"	white-space:nowrap;",
				"	display: inline-block;",
				"	text-overflow: ellipsis;",
				"	-ms-text-overflow: ellipsis;",
				"}",
				"",
				"<strong>//Find all input text, email, password</strong>",
				"<strong>input</strong>[<strong>type=text</strong>]:-moz-ui-invalid,<strong>input</strong>[<strong>type=email</strong>]:-moz-ui-invalid,<strong>input</strong>[<strong>type=password</strong>]:-moz-ui-invalid {",
				"	box-shadow: 0 0 1.5px 1px transparent;",
				"}",
				"<strong>//Find only Radio Button and Check Box</strong>",
				"<strong>input</strong>[type=\"<strong>radio</strong>\"], <strong>input</strong>[type=\"<strong>checkbox</strong>\"]{",
				"	margin: 0px;",
				"}",
				"",
				"<strong>//Keep diplay pin in Google Map from bootstrap</strong>",
				".map-view{",
				"	width: 68%;",
				"	float: left;",
				"}",
				".gllpLatlonPicker{",
				"	margin: 20px 0;",
				"}",
				".gllpMap{",
				"	width: 500px;",
				"	height: 250px;",
				"}",
				".gllpMap img{",
				"	max-width: inherit;",
				"}",
				"",
				"</pre></div>",
				"<strong>5. Checkbox Tips:</strong>",
				"<div class='code_container'><pre class='code_block'><strong>//Create html code</strong>",
				"<code><</code>div id=\"<strong>badgesListItem</strong>\"<code>></code>",
				"	<code><</code>input type=\"checkbox\" value=\"1\"/<code>></code>",
				"	<code><</code>input type=\"checkbox\" value=\"2\"/<code>></code>",
				"	<code><</code>input type=\"checkbox\" value=\"3\"/<code>></code>",
				"	<code><</code>input type=\"checkbox\" value=\"4\"/<code>></code>",
				"	<code><</code>input type=\"checkbox\" value=\"5\"/<code>></code>",
				"	<code><</code>input type=\"checkbox\" value=\"6\"/<code>></code>",
				"	<code><</code>input type=\"checkbox\" value=\"7\"/<code>></code>",
				"<code><</code>/div<code>></code>",
				"<strong>//Get all values from check box list</strong>",
				"var badgeIdsList = [];",
				"$(\"<strong>#badgesListItem input</strong>\").each(function(){",
				"	var checkboxItem = $(this);",
				"	if(checkboxItem.is(\"<strong>:checked</strong>\")){",
				"		badgeIdsList.push(checkboxItem.val());",
				"	}",
				"});",
				"</pre></div>",
			]
};