var tip6 = {
	id : 6,
	title : "Embed Font",
	urlIds : [63, 64, 65, 66],
	content : [
				"<h4>Introduction:</h4>",
				"Browsers can support any fonts as posible. If no font provided, browsers will use default font. But custom font also can create as embed font for each language.",
				"<h4>Purpose:</h4>",
				"To create custom embed font for specific language for each country.",
				"<strong>1. Russia Embed font:</strong>",
				"<div class='code_container'><pre class='code_block'>//Create font name as \"<strong>NGT77</strong>\"",
				"<strong>@font-face {</strong>",
				"    font-family: '<strong>NGT77</strong>';",
				"    src: url('<strong>fonts/NGT77.eot</strong>') format('<strong>embedded-opentype</strong>'),",
				"         url('<strong>fonts/NGT77.ttf</strong>') format('<strong>truetype</strong>'),",
				"         url('<strong>fonts/NGT77.svg</strong>') format('<strong>svg</strong>'),",
				"         url('<strong>fonts/NGT77.woff</strong>') format('<strong>woff</strong>');",
				"    font-weight: normal;",
				"    font-style: normal;",
				"",
				"}</strong>",
				"//Create font name as \"<strong>Trade_Gothic_LT_Bold_Condensed</strong>\"",
				"<strong>@font-face {</strong>",
				"    font-family: '<strong>Trade_Gothic_LT_Bold_Condensed</strong>';",
				"    src: url('<strong>fonts/Trade_Gothic_LT_Bold_Condensed.eot</strong>') format('<strong>embedded-opentype</strong>'),",
				"         url('<strong>fonts/Trade_Gothic_LT_Bold_Condensed.ttf</strong>') format('<strong>truetype</strong>'),",
				"         url('<strong>fonts/Trade_Gothic_LT_Bold_Condensed.svg</strong>') format('<strong>svg</strong>'),",
				"         url('<strong>fonts/Trade_Gothic_LT_Bold_Condensed.woff</strong>') format('<strong>woff</strong>');",
				"    font-weight: normal;",
				"    font-style: normal;",
				"",
				"}</strong>",
				"//Apply",
				"<strong>html, html *{</strong>",
				"	margin:0;",
				"	padding:0;",
				"	font-family: \"<strong>Trade_Gothic_LT_Bold_Condensed</strong>\";",
				"<strong>}</strong>",
				"</pre></div>",
				"<strong>1. Khmer Embed font:</strong>",
				"<div class='code_container'><pre class='code_block'>//Create font name as \"<strong>Khmer OS</strong>\"",
				"<strong>@font-face {</strong>",
				"	font-family: \"<strong>Khmer OS</strong>\";",
				"	src: url(\"<strong>KhmerOS.eot</strong>\");/* IE support */",
				"	src: local('<strong>Khmer OS</strong>'),url(<strong>KhmerOS.ttf</strong>) format('<strong>truetype</strong>');/* Firefox3.5>, Saferi3.1>*/",
				"<strong>}</strong>",
				"//Apply",
				"<strong>body{</strong>",
				"	font-family: \"<strong>Khmer OS</strong>\";",
				"<strong>}</strong>",
				"//Create font name as \"<strong>Khmer OS</strong>\"",
				"<strong>@font-face {</strong>",
				"    font-family: \"<strong>Khmer OS</strong>\";",
				"    font-style:  normal;",
				"    font-weight: normal;",
				"    font-size: 14pt;",
				"    src: url(<strong>KHMEROS0.eot</strong>);",
				"    src: local(\"☺\"),",
				"         url(<strong>KhmerOS.ttf</strong>) format('<strong>truetype</strong>');",
				"<strong>}</strong>",
				"//Create font name as \"<strong>Hanuman</strong>\"",
				"<strong>@font-face {</strong>",
				"  font-family: <strong>Hanuman</strong>;",
				"  font-style: normal;",
				"  font-weight: normal;",
				"  src: local(\"☺\"),",
				"    url(<strong>Hanuman.ttf</strong>) format('<strong>truetype</strong>'),",
				"    url('<strong>http://themes.googleusercontent.com/font?kit=r19pdQKU01vNMZlSCum2Ag</strong>') format('<strong>woff</strong>');",
				"<strong>}</strong>",
				"//Create font name as \"<strong>Kaoh Kong</strong>\"",
				"<strong>@font-face {</strong>",
				"    font-family: \"<strong>Kaoh Kong</strong>\";",
				"    font-style:  normal;",
				"    font-weight: normal;",
				"    font-size: 14pt;",
				"    src: url(<strong>KAOHKON0.eot</strong>);",
				"<strong>}</strong>",
				"</pre></div>",
			]
};