var tip2 = {
	id : 2,
	title : "JQuery and Bootstrap Date Picker",
	urlIds : [16],
	content : [
	           "<h4>Introduction:</h4>",
	           "Date Picker is calendar date, so it is easy for us to pick up date from calendar.",
	           "JQuery Date Picker provides us the tool to create calendar append with input field of HTML element.",
	           "Bootstrap Date Picker also give us the tool to create calendar with sexy interface but it is hard to format date.",
	           "That is the why JQuery Date Picker and Bootstrap Date Picker combine together to make it easily for implementation.",
	           "<h4>Purpose:</h4>",
	           "Keep sexy interface as Bootstrap Date Picker has and easy to format, Jquery and Bootstrap Date Picker are combined.",
	           "<h4>Step to do:</h4>",
	           "<strong>1. Import JQuery and Bootstrap Library:</strong>",
	           "<div class='code_container'><pre class='code_block'><code><</code>link rel='stylesheet' type=\"text/css\" href='/css/bootstrap.min.css' /<code>></code>",
	           "<code><</code>link rel='stylesheet' type=\"text/css\" href='/css/datepicker.css' /<code>></code>",
	           "<code><</code>link rel='stylesheet' type=\"text/css\" href='/css/jquery-ui-1.10.2.custom.min.css' /<code>></code>",
	           "<code><</code>script type=\"text/javascript\" src=\"/js/jquery-1.9.1.min.js\"<code>></code><code><</code>/script<code>></code>",
	           "<code><</code>script type=\"text/javascript\" src=\"/js/jquery-ui-1.10.2.custom.min.js\"<code>></code><code><</code>/script<code>></code>",
	           "<code><</code>script type=\"text/javascript\" src=\"/js/bootstrap.min.js\"<code>></code><code><</code>/script<code>></code></pre></div>",
	           "<strong>2. Input field with calendar icon</strong>",
	           "<div class='code_container'><pre class='code_block'><code><</code>input type=\"text\" id=\"<strong>startDatePicker</strong>\" name=\"<strong>startDatePicker</strong>\" placeholder=\"MMM DD, YYYY\" readOnly /<code>></code>",
	           "<code><</code>span id=\"startDateIcon\" class=\"add-on date-cursor\"<code>></code><code><</code>i class=\"icon-calendar\"<code>></code><code><</code>/i<code>></code><code><</code>/span<code>></code>",
	           "<code><</code>input type=\"hidden\" id=\"<strong>offer_startDate</strong>\" name=\"<strong>offer_startDate</strong>\" placeholder=\"Start Date\" /<code>></code></pre></div>",
	           "<strong>3. Configure in Javascript</strong>",
	           "<div class='code_container'><pre class='code_block'><strong><code><</code>script type=\"text/javascript\"<code>></code></strong>",
	           "	<strong>$(function() {</strong>",
	           "		<strong>$(\"#startDatePicker\").datepicker({</strong>",
	           "			altField: \"#<strong>offer_startDate</strong>\",",
	           "			altFormat: \"@\",",
	           "			dateFormat: \"MM dd, yy\",",
	           "			yearRange: \"c-70:c+20\",//c is current year",
	           "			changeMonth: true,",
	           "			changeYear: true,",
	           "			onSelect:function(){<strong>validateOfferDateRang($(this))</strong>},",
	           "			onChangeMonthYear:function(y, m, i){",
	           "				<strong>setDateForChangeMonthYear($(this), y, m, i);</strong>",
	           "			},",
	           "			beforeShow: function(){",
	           "				setTimeout(function(){",
	           "					$('.ui-datepicker').css({'z-index' : '10003'});",
	           "				}, 0);",
	           "			}",
	           "		<strong>});</strong>",
	           "		",
	           "		//Load to set value to date picker",
	           "		$( \"#startDatePicker\" ).datepicker( \"setDate\", <strong>convertLongToDate(value)</strong> );",
	           "	<strong>});</strong>",
	           "	",
	           "	<strong>function setDateForChangeMonthYear(dateSelector, y, m, i){</strong>",
	           "		var d = i.selectedDay;",
	           "		dateSelector.datepicker('setDate', new Date(y, m - 1, d));//display in field",
	           "		<strong>validateOfferDateRang(dateSelector);</strong>",
	           "	<strong>}</strong>",
	           "	",
	           "	<strong>function validateOfferDateRang(dateSelector){</strong>",
	           "		if($(\"#startDatePicker\").val() == \"\" || $(\"#endDatePicker\").val() ==\"\"){",
	           "			return false;",
	           "		}",
	           "		",	
	           "		if($(\"#offer_startDate\").val() > $(\"#offer_endDate\").val()){",
	           "			alert(\"End date cannot be less than start date\");",
	           "			dateSelector.val(\"\");",
	           "			dateSelector.focus();",
	           "		}",
	           "	<strong>}</strong>",
	           "	",
	           "	<strong>function convertLongToDate(milis){</strong>",
	           "		var date = new Date(milis);",
	           "		",
	           "		return date.dateFormat(\"#MMMM# #DD#, #YYYY#\");",
	           "	<strong>}</strong>",
	           "	",
	           "	<strong>Date.prototype.dateFormat = function(formatString){</strong>",
	           "		var YYYY,YY,MMMM,MMM,MM,M,DDDD,DDD,DD,D,hhh,hh,h,mm,m,ss,s,ampm,AMPM,dMod,th;",
	           "		var dateObject = this;",
	           "		YY = ((YYYY=dateObject.getFullYear())+\"\").slice(-2);",
	           "		MM = (M=dateObject.getMonth()+1)<10?('0'+M):M;",
	           "		MMM = (MMMM=[\"January\",\"February\",\"March\",\"April\",\"May\",\"June\",\"July\",\"August\",\"September\",\"October\",\"November\",\"December\"][M-1]).substring(0,3);",
	           "		DD = (D=dateObject.getDate())<10?('0'+D):D;",
	           "		DDD = (DDDD=[\"Sunday\",\"Monday\",\"Tuesday\",\"Wednesday\",\"Thursday\",\"Friday\",\"Saturday\"][dateObject.getDay()]).substring(0,3);",
	           "		th=(D>=10&&D<=20)?'th':((dMod=D%10)==1)?'st':(dMod==2)?'nd':(dMod==3)?'rd':'th';",
	           "		formatString = formatString.replace(\"#YYYY#\",YYYY).replace(\"#YY#\",YY).replace(\"#MMMM#\",MMMM).replace(\"#MMM#\",MMM).replace(\"#MM#\",MM).replace(\"#M#\",M).replace(\"#DDDD#\",DDDD).replace(\"#DDD#\",DDD).replace(\"#DD#\",DD).replace(\"#D#\",D).replace(\"#th#\",th);",
	           "		",
	           "		h=(hhh=dateObject.getHours());",
	           "		if (h==0) h=24;",
	           "		if (h>12) h-=12;",
	           "		hh = h<10?('0'+h):h;",
	           "		AMPM=(ampm=hhh<12?'am':'pm').toUpperCase();",
	           "		mm=(m=dateObject.getMinutes())<10?('0'+m):m;",
	           "		ss=(s=dateObject.getSeconds())<10?('0'+s):s;",
	           "		return formatString.replace(\"#hhh#\",hhh).replace(\"#hh#\",hh).replace(\"#h#\",h).replace(\"#mm#\",mm).replace(\"#m#\",m).replace(\"#ss#\",ss).replace(\"#s#\",s).replace(\"#ampm#\",ampm).replace(\"#AMPM#\",AMPM);",
	           "	<strong>}</strong>",
	           "<strong><code><</code>/script<code>></code></strong></pre></div>"
	           ]
};